

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dummy
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update





server:
  port: 8888

upload:
  directory: D:\learnings\spring-uploadfile\src\main\resources\uploaded\
